### ISSUE TITLE
Support for unique/distinct validation

### ISSUE THREAD

**Issue by dmargol1** [TMiguelT/PandasSchema#1]
Could there be a validator that checked to see if a column is made only of unique values?

Basically, if `len(df[df[col].duplicated()]) > 0` then it invalid.

**Comment by markusbaden** [comment]
You can try using a custom validation like the one below. The lambda function returns a series with `False` for every duplicate which is probably what you want

```python
CustomSeriesValidation(
    validation=lambda x: ~x.duplicated(keep=False),
    message='is not unique',
)
```

**Comment by TMiguelT** [comment]
Added this as `IsDistinctValidation`: https://tmiguelt.github.io/PandasSchema/_modules/pandas_schema/validation.html#IsDistinctValidation

**Comment by dmargol1** [comment]
Thanks!
