### ISSUE TITLE
Cannot set `allow_missing=True` for numeric column

### ISSUE THREAD

**Issue by caddac** [TMiguelT/PandasSchema#14]
Probably related #5 and #13, I can't set `allow_missing=True` on a column that is of a numeric type, then run a `InRangeValidation` on that column.
I get the error `raise AttributeError("Can only use .str accessor with string "
AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas` at https://github.com/TMiguelT/PandasSchema/blob/1742791a8e6fa22380d6f49693148de99fd7ec5d/pandas_schema/validation.py#L87

**Comment by caddac** [comment]
https://github.com/TMiguelT/PandasSchema/pull/15

**Comment by TMiguelT** [comment]
Closed by #15
