### ISSUE TITLE
Question: How do you do validation for two columns that depend on each other

### ISSUE THREAD

**Issue by dtamez** [TMiguelT/PandasSchema#25]
Easy example: You have a column for phone and a column for email.  One of them has to be supplied - they can't both be blank.  

I can create a new column that has the other two columns combined and run a custom validator on that - but if there's a built in way I'd like to know.

**Comment by TMiguelT** [comment]
Currently, you can't. See #2. This is something I've been meaning to get to for a while, but of course a PR would be the fastest way to get this implemented.

**Comment by joolius** [comment]
May I add that it would be useful to be able to construct validation on arbitrary number of columns, not just two.

**Comment by Abhisek1994Roy** [comment]
Any update on validations with 1 or more columns?

**Comment by TMiguelT** [comment]
Sorting this out has ended up requiring a whole rewrite to the library. My lack of spare time, plus losing a few days of uncommitted work has unfortunately slowed this down. There is no way to do this within the confines of the library as is.

**Comment by TMiguelT** [comment]
I'm closing this issue because it's strongly related to #2, and any work that closes it will close this also.
