### ISSUE TITLE
CustomValidator Error: Use `not` instead of `~` 

### ISSUE THREAD

**Issue by Ghost---Shadow** [TMiguelT/PandasSchema#32]
My CustomValidator returned `True` and `False`. But, 

line 85: validation.py

says

```
simple_validation = ~self.validate(series)
```

Which does a bitwise not.

<img width="628" alt="Screen Shot 2020-04-30 at 10 14 10 AM" src="https://user-images.githubusercontent.com/7743925/80673000-bc473980-8acb-11ea-967b-d05103073d4b.png">

I think the documentation needs to be more clear about the expectation or we should change to line to.

```
simple_validation = not self.validate(series)
```

**Comment by TMiguelT** [comment]
If you're using a [`CustomSeriesValidation`](https://tmiguelt.github.io/PandasSchema/#pandas_schema.validation.CustomSeriesValidation) (which you are evidently doing here), the documentation says that you must return a boolean *Series*, from your validation function, not a single boolean.

If you want to return a single boolean for each cell, you should use `CustomElementValidation`, or if you want to return a single boolean for the whole Series, you can attempt to mimic [`IsDtypeValidation`](https://github.com/TMiguelT/PandasSchema/blob/eae711871e350519d6df48547d3000a7b6fedcb3/pandas_schema/validation.py#L217-L237)

**Comment by TMiguelT** [comment]
Incidentally, this behaviour will be much nicer in the next major version. You will be able to return a single boolean to indicate that the whole Series has passed/failed the validation, or a boolean Series which will apply for each position in the Series.
