### ISSUE TITLE
Question: How to validate if all value in column are unique?

### ISSUE THREAD

**Issue by kevalkothari** [TMiguelT/PandasSchema#34]
Also is it possible to validate combination of two field value as unique ?

**Comment by TMiguelT** [comment]
> How to validate if all value in column are unique

Use [`IsDistinctValidation`](https://tmiguelt.github.io/PandasSchema/#pandas_schema.validation.IsDistinctValidation)

> Also is it possible to validate combination of two field value as unique ?

Currently, no, because the current release only supports per-Series validations. In the new major version this should be possible. I'll update this issue when it's released.

**Comment by TMiguelT** [comment]
Closing in favour of the more general #57 that I just opened.
