### ISSUE TITLE
Validation on one column which is dependent on other column of dataframe

### ISSUE THREAD

**Issue by nishanttayal** [TMiguelT/PandasSchema#55]
I am not sure if this library currently supports this feature but I am looking for a way through which I can build custom validation of one column based on values present in another column.
For Example -

`Name, Salary, Department`
`Rob, 5500, Aviation`
`Bob, 1000, Facilities`
`Tom, 6000, IT`

In this dataset, I wanted to check if a salary is greater than 5000 when the department is "Aviation", salary greater than 1000 if Department is "Facilities" and so on.

**Comment by melvinpradep** [comment]
I too have a similar problem statement to solve, any inputs is much appreciated.

**Comment by TMiguelT** [comment]
Closing in favour of the more general #57 that I just opened.
