### ISSUE TITLE
Load schema from db

### ISSUE THREAD

**Issue by oshribr** [TMiguelT/PandasSchema#6]
What the way to load schema from the DB?

**Comment by TMiguelT** [comment]
If you are storing your data in a a relational (or other) database, I recommend using the database's inbuilt validation facilities (e.g. https://www.postgresql.org/docs/current/static/ddl-constraints.html). PandasSchema is more useful for situations where your data is stored in CSV/TSV files that you are probably manipulating with Pandas, and you also need data validation.
